### ISSUE TITLE
demo site doesn't work?

### ISSUE THREAD

**Issue by redxman** [EasyAbp/Forum#2]
demo site doesn't work?
there is not management  page.

**Comment by gdlcf88** [comment]
It seems that the demo site https://forum.samples.easyabp.io actually belongs to the [CacheManagement module](https://github.com/EasyAbp/CacheManagement). Can you check it? @hueifeng

**Comment by Tranphat-freelancer** [comment]
When I use DynamicEntity i can't call the modal form of CreateModel, it just changes the UI a bit but doesn't show the modal. This also happens with Create EntityUI too is this a bug? @gdlcf88 

![image](https://user-images.githubusercontent.com/101075772/177920167-47afab61-8a47-4eb2-bd95-f78541bee3e6.png)

**Comment by hueifeng** [comment]
Hello, we haven't deployed this project yet, and we will migrate all Demo on a large scale in the future.

**Comment by gdlcf88** [comment]
I found that all the nonexistent domains fall back to the demo of the CacheManagement module. Try https://forum123.samples.easyabp.io/

**Comment by redxman** [comment]
Hope to deploy demo site soon :)

**Comment by gdlcf88** [comment]
It will come soon.
